version: '3.7'

services:
  ts-node-docker:
    build:
      context: .  #where to find ur docker file, '.' means current dir
      dockerfile: Dockerfile
      target: base
    volumes:
      - .:/usr/src/app
    container_name: ts-node-docker
    ports:
      - '3000:3000'
    links:
      - mongo
    command: npm run start
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'